title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://katerinanavab.github.io/webdocs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "logo-introcs.png"
