title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://katerinanavab.github.io/webdocs

aux_links:
  "Instructor Site":
    - "https://coderina.dev"

logo: "logo-introcs.png"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Katerina Navab. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT License.</a> This site is powered by <a href=\"https://pages.github.com/\">GitHub Pages</a> and uses <a href=\"https://github.com/just-the-docs">Just the Docs</a>, a documentation theme for Jekyll."
