title: Web Docs
description: Course materials for Pre-AP Computer Science
theme: just-the-docs

url: https://katerinanavab.github.io/webdocs

logo: "assets/logo-webdocs.png"
favicon_ico: "favicon.ico"

aux_links_new_tab: true
aux_links:
  "BLACKBAUD":
    - "https://bwl.myschoolapp.com/app#login"
  "REPLIT":
    - "https://replit.com/~"
    
back_to_top: true
back_to_top_text: "⬆️ BACK TO TOP"

liquid:
   error_mode: strict
   strict_filters: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: myyellow
  important:
    title: Important
    color: myblue
  new:
    title: New
    color: mygreen
  note:
    title: Note
    color: mypurple
  warning:
    title: Warning
    color: myred
