title: Web Docs
description: Course materials for Intro Computer Science
theme: just-the-docs

url: https://katerinanavab.github.io/webdocs

aux_links:
  "Instructor Site":
    - "https://coderina.dev"

logo: "logo-introcs.png"
favicon_ico: "logo-introcs.png"

back_to_top: true
back_to_top_text: "⬆️ BACK TO TOP"
